arch:
  - amd64
  - ppc64le
  
sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
#  - "13"
#  - "14"
#  - "15"
   -  "node"
   -  "lts/*"
   
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint
    - node_js: "6"
      arch: ppc64le
      env: TEST_SUITE=lint
before_script:
  - npm run test:prepare
script: npm run-script $TEST_SUITE
